{% set name = "about-time" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/about-time-{{ version }}.tar.gz
  sha256: 6a538862d33ce67d997429d14998310e1dbfda6cb7d9bbfbf799c4709847fece

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: True # [py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - about_time
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rsalmei/about-time
  summary: Easily measure timing and throughput of code blocks, with beautiful human friendly representations.
  description: |
    A cool helper for tracking time and throughput of code blocks, with beautiful human friendly renditions.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/rsalmei/about-time
  doc_url: https://github.com/rsalmei/about-time/blob/main/README.md

extra:
  recipe-maintainers:
    - Brainor
