{% set name = "about-time" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/about-time-{{ version }}.tar.gz
  sha256: 9918934ecba7054f938fad1e5171fb70b944975c8349bf2663116a654c9ff35f
  patches:
    - setup-with-encoding.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - about_time
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rsalmei/about-time
  summary: Easily measure timing and throughput of code blocks, with beautiful human friendly representations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Brainor
